package com.canonal.tracker_domain.use_case

import com.canonal.tracker_domain.model.MealType
import com.canonal.tracker_domain.model.TrackableFood
import com.canonal.tracker_domain.model.TrackedFood
import com.canonal.tracker_domain.repository.TrackerRepository
import java.time.LocalDate
import kotlin.math.roundToInt

class TrackFoodUseCase(private val trackerRepository: TrackerRepository) {
    suspend operator fun invoke(
        trackableFood: TrackableFood,
        mealType: MealType,
        amount: Int,
        date: LocalDate
    ) {
        trackerRepository.insertTrackedFood(
            // id is generated by room automatically
            trackedFood = TrackedFood(
                name = trackableFood.name,
                carbs = ((trackableFood.carbsPer100g / 100f) * amount).roundToInt(),
                protein = ((trackableFood.proteinPer100g / 100f) * amount).roundToInt(),
                fat = ((trackableFood.fatPer100g / 100f) * amount).roundToInt(),
                calories = ((trackableFood.caloriesPer100g / 100f) * amount).roundToInt(),
                imageUrl = trackableFood.imageUrl,
                mealType = mealType,
                amount = amount,
                date = date
            )
        )
    }
}
